groups_resources
rmilushev/studygroup pull request #8
Opened 2020-12-02 17:12 UTC by N-Patarov

2020-12-02 17:17 UTC, rmilushev requested changes

2020-12-02 17:17 UTC, rmilushev commented on lib/studygroup_web/router.ex
> +  resources "/groups", GroupsController
Please, remove it from here.

2020-12-02 17:17 UTC, rmilushev commented on lib/studygroup_web/router.ex
> +    put "/groups", GroupsController, :create
Please, change to :
```
resources "/groups", GroupsController
```

2020-12-02 17:50 UTC, ykostov commented on lib/studygroup/groups/group.ex
> +
gotta add email field with value "string"

2020-12-03 18:34 UTC, ykostov requested changes
Good job on the self-initiative, just make sure to delete line 6 on routes.ex

2020-12-03 18:34 UTC, ykostov commented on lib/studygroup_web/router.ex
> +  resources "/groups", GroupController
Please, remove this one from this - you don't need it

2020-12-03 18:34 UTC, ykostov commented on lib/studygroup_web/templates/layout/_user_menu.html.eex
> +  <%= link "Sign in", to: Routes.user_session_path(@conn, :new), class: "btn btn-sm btn-primary" %>
Good job on pairing the links

2020-12-03 18:34 UTC, ykostov commented on lib/studygroup_web/templates/layout/root.html.leex
> +              <!-- <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "btn btn-sm btn-link" %>-->
Well done on just muting that item, could be useful later

2020-12-03 19:19 UTC, rmilushev approved these changes

2020-12-03 19:56 UTC, ykostov approved these changes
Ready to Merge

2020-12-03 19:57 UTC, ykostov approved these changes

2020-12-03 19:59 UTC, ykostov approved these changes
Good to go

2020-12-03 21:32 UTC, merged